{
 "title": "Poputkee",
 "description": "Dealee project dashboard",
 "tags": [
  "dealee",
  "slavaproject"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prometheus", "label": "Datasource", "query": "prometheus" },
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Business",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Driver Orders 5m",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum by (status)(max without (pod,instance)(increase(slava_project_driver_orders{}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "General Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Total RPS",
   "type": "stat",
   "description": "Overall requests per second to the whole service",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "round(sum(max without (pod,instance)(irate(slava_project_requests_latency_count[$__rate_interval]))), 0.001)",
     "query": "round(sum(irate(PHP_monolith_api_requests_total_v2[2m])), 0.001)"
    }
   ]
  },
  {
   "title": "% Success (5m)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(slava_project_requests_latency_count{status!~\"[4-5].*\"}[$__rate_interval])) / sum(rate(slava_project_requests_latency_count{status!=\"401\"}[$__rate_interval]))",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Code status (1m)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (status)(max without (pod,instance)(increase(slava_project_requests_latency_count{status=~\"(1|2).*\"}[$__rate_interval])))",
     "legendFormat": "Code: {{status}}"
    },
    {
     "expr": "sum by (status)(max without (pod,instance)(increase(slava_project_requests_latency_count{status=~\"4.*\"}[$__rate_interval])))",
     "legendFormat": "Code: {{status}}"
    },
    {
     "expr": "sum by (status)(max without (pod,instance)(increase(slava_project_requests_latency_count{status=~\"5.*\"}[$__rate_interval])))",
     "legendFormat": "Code: {{status}}"
    }
   ]
  },
  {
   "title": "Latencies",
   "type": "stat",
   "description": "Popular percentile latencies",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(max without (pod,instance)(rate(slava_project_requests_latency_bucket[$__rate_interval]))) by (le))",
     "legendFormat": "p95",
     "query": "histogram_quantile(0.95, sum(rate(PHP_monolith_api_duration_seconds_v2_bucket[5m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.90, sum(max without (pod,instance)(rate(slava_project_requests_latency_bucket[$__rate_interval]))) by (le))",
     "legendFormat": "p90",
     "query": "histogram_quantile(0.90, sum(rate(PHP_monolith_api_duration_seconds_v2_bucket[5m])) by (le))"
    },
    {
     "expr": "histogram_quantile(0.5, sum(max without (pod,instance)(rate(slava_project_requests_latency_bucket[$__rate_interval]))) by (le))",
     "legendFormat": "p50",
     "query": "histogram_quantile(0.5, sum(rate(PHP_monolith_api_duration_seconds_v2_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Top 20 API Request",
   "type": "table",
   "gridPos": { "h": 23, "w": 6, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(20, sum by (method,url)(max without (pod,instance)(rate(slava_project_requests_latency_count{}[$__rate_interval]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Successful API requests (5m)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method,url) (max without (pod,instance)(increase(slava_project_requests_latency_count{status=~\"[4-5].*\"}[$__rate_interval]))) / \n(sum by (method,url) (max without (pod,instance)(increase(slava_project_requests_latency_count{}[$__rate_interval]))) -\n(sum by (method,url) (max without (pod,instance)(increase(slava_project_requests_latency_count{status=~\"401\"}[$__rate_interval])))))",
     "legendFormat": "{{method}} URL:  {{url}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 18, "x": 6, "y": 24 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(max without (pod,instance)(rate(slava_project_requests_latency_bucket{}[$__rate_interval]))) by (le, method, url))",
     "legendFormat": "{{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Top 10 Failed API Request (400-500 HTTP status code)",
   "type": "table",
   "description": "400-500 HTTP status code",
   "gridPos": { "h": 12, "w": 6, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum by (method,url) (max without (pod,instance)(increase(slava_project_requests_latency_count{status=~\"400|402|403|404|5.*\"}[$__rate_interval]))))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed API requests (400|500 STATUS CODE)",
   "type": "timeseries",
   "description": "Failed API requests (400|500 STATUS CODE)",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method,url,status) (max without (pod,instance)(increase(slava_project_requests_latency_count{status=~\"400|402|403|404|5.*\"}[$__rate_interval])))",
     "legendFormat": "{{method}} URL:  {{url}} - status: {{status}}"
    }
   ]
  }
 ]
}